version: "3.3"

services:

  dashboard:
    image: ghcr.io/oakestra/dashboard:latest
    ports:
      - '80:80'
    restart: unless-stopped
    container_name: oaekstra-frontend-container
    environment:
      - API_ADDRESS=${SYSTEM_MANAGER_URL}:10000

  # System Manager REST API of Root Orchestrator
  system_manager:
    image: ghcr.io/oakestra/oakestra/root-system-manager:latest
    hostname: system_manager
    container_name: system_manager
    network_mode: "host"
    depends_on:
      - mongo_root
      - cloud_scheduler
      - root_service_manager
    environment:
      - CLOUD_MONGO_URL=localhost
      - CLOUD_MONGO_PORT=10007
      - CLOUD_SCHEDULER_URL=localhost
      - CLOUD_SCHEDULER_PORT=10004
      - NET_PLUGIN_URL=localhost
      - NET_PLUGIN_PORT=10099


  # MongoDB in Root Orchestrator
  mongo_root:
    image: mongo:3.6
    container_name: mongo
    hostname: mongo
    network_mode: "host"
    volumes:
      - 'mongodb_data:/mongodb'
    command: mongod --port 10007

  # cluster-level mongoDB
  mongo_rootnet:
    image: mongo:3.6
    container_name: mongo_net
    hostname: mongo_net
    network_mode: "host"
    volumes:
      - 'mongodb_net_data:/mongodb'
    command: mongod --port 10008


  # Cluster Manager
  root_service_manager:
    image: ghcr.io/oakestra/oakestra-net/root-service-manager:latest
    container_name: root_service_manager
    hostname: root_service_manager
    network_mode: "host"
    environment:
      - MY_PORT=10099
      - SYSTEM_MANAGER_URL=localhost
      - SYSTEM_MANAGER_PORT=10000
      - CLOUD_MONGO_URL=localhost
      - CLOUD_MONGO_PORT=10008
    depends_on:
      - mongo_rootnet


  # Redis for the Cloud Scheduler
  redis:
    image: redis
    hostname: redis
    container_name: redis
    network_mode: "host"
    command: redis-server --requirepass cloudRedis


  grafana:
    image: grafana/grafana
    hostname: grafana
    container_name: grafana
    network_mode: "host"


  # Cloud Scheduler
  cloud_scheduler:
    image: ghcr.io/oakestra/oakestra/cloud-scheduler:latest
    container_name: cloud_scheduler
    hostname: cloud_scheduler
    network_mode: "host"
    environment:
      - MY_PORT=10004
      - SYSTEM_MANAGER_URL=localhost
      - SYSTEM_MANAGER_PORT=10000
      - CLOUD_MONGO_URL=localhost
      - CLOUD_MONGO_PORT=10007
      - REDIS_ADDR=redis://:cloudRedis@localhost:6379
    depends_on:
      - redis
      - mongo_root

  # MQTT
  mqtt:
    image: eclipse-mosquitto:1.6
    hostname: mqtt
    container_name: mqtt
    network_mode: "host"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /mosquitto/data
      - /mosquitto/log
    healthcheck:
      test: [ "CMD-SHELL", "timeout -t 5 mosquitto_sub -t '$$SYS/#' -C 1 | grep -v Error || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 6


  # cluster-level mongoDB
  mongo_cluster:
    image: mongo:3.6
    container_name: cluster_mongo
    hostname: cluster_mongo
    network_mode: "host"
    volumes:
      - 'mongodb_cluster_data:/mongodb'
    command: mongod --port 10107

# cluster-level mongoDB
  mongo_clusternet:
    image: mongo:3.6
    container_name: cluster_mongo_net
    hostname: cluster_mongo_net
    network_mode: "host"
    volumes:
      - 'mongodb_cluster_net_data:/mongodb'
    command: mongod --port 10108


# Cluster Manager
  cluster_service_manager:
    image: ghcr.io/oakestra/oakestra-net/cluster-service-manager:latest
    container_name: cluster_service_manager
    hostname: cluster_service_manager
    network_mode: "host"
    environment:
      - MY_PORT=10110
      - MQTT_BROKER_PORT=10003
      - MQTT_BROKER_URL=localhost
      - ROOT_SERVICE_MANAGER_URL=localhost
      - ROOT_SERVICE_MANAGER_PORT=10099
      - SYSTEM_MANAGER_URL=localhost
      - SYSTEM_MANAGER_PORT=10000
      - CLUSTER_MONGO_URL=localhost
      - CLUSTER_MONGO_PORT=10108
    depends_on:
      - mongo_clusternet
      - mqtt

# Cluster Manager
  cluster_manager:
    image: ghcr.io/oakestra/oakestra/cluster-manager:latest
    container_name: cluster_manager
    hostname: cluster_manager
    command: bash -c 'sleep 2; python cluster_manager.py'
    network_mode: "host"
    environment:
      - MY_PORT=10100
      - SYSTEM_MANAGER_URL=localhost
      - SYSTEM_MANAGER_PORT=10000
      - CLUSTER_SERVICE_MANAGER_ADDR=localhost
      - CLUSTER_SERVICE_MANAGER_PORT=10110
      - CLUSTER_MONGO_URL=localhost
      - CLUSTER_MONGO_PORT=10107
      - CLUSTER_SCHEDULER_URL=localhost
      - CLUSTER_SCHEDULER_PORT=10105
      - MQTT_BROKER_URL=localhost
      - MQTT_BROKER_PORT=10003
      - CLUSTER_NAME=${CLUSTER_NAME}
      - CLUSTER_LOCATION=${CLUSTER_LOCATION}
    depends_on:
      - mongo_cluster
      - mqtt
      - cluster_scheduler
      - cluster_service_manager
      - system_manager


  # Cluster Scheduler
  cluster_scheduler:
    image: ghcr.io/oakestra/oakestra/cluster-scheduler:latest
    container_name: cluster_scheduler
    hostname: cluster_scheduler
    network_mode: "host"
    environment:
      - MY_PORT=10105
      - CLUSTER_MANAGER_URL=localhost
      - CLUSTER_MANAGER_PORT=10100
      - CLUSTER_MONGO_URL=localhost
      - CLUSTER_MONGO_PORT=10107
      - REDIS_ADDR=redis://:clusterRedis@localhost:6479
    depends_on:
      - cluster_redis
      - mongo_cluster


  # Redis for the Cluster Scheduler as Job Queue
  cluster_redis:
    image: redis
    hostname: cluster_redis
    container_name: cluster_redis
    network_mode: "host"
    command: redis-server --requirepass clusterRedis --port 6479


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    network_mode: "host"
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - cluster_manager

volumes:
  mongodb_data:
    driver: local
  mongodb_net_data:
    driver: local
  mongodb_cluster_data:
    driver: local
  mongodb_cluster_net_data:
    driver: local
